### ISSUE TITLE
`mlflow --version` crashed after installed with conda-forge on python 3.7.3 virtual env

### ISSUE THREAD

**Issue by ShumzZ** [conda-forge/mlflow-feedstock#21]
Issue: I was trying to use `mlflow` in an virtual env so I created one with conda-forge, the installation was successful, but when I tried to check version with `mlflow --version`, it crashed with the following:
```
$ mflow --version
Traceback (most recent call last):
  File "/Users/user/miniconda/envs/mlflowtest/bin/mlflow", line 10, in <module>
    sys.exit(cli())
  File "/Users/user/miniconda/envs/mlflowtest/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/miniconda/envs/mlflowtest/lib/python3.7/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/user/miniconda/envs/mlflowtest/lib/python3.7/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/Users/user/miniconda/envs/mlflowtest/lib/python3.7/site-packages/click/core.py", line 1089, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/Users/user/miniconda/envs/mlflowtest/lib/python3.7/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/user/miniconda/envs/mlflowtest/lib/python3.7/site-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/Users/user/miniconda/envs/mlflowtest/lib/python3.7/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/Users/user/miniconda/envs/mlflowtest/lib/python3.7/site-packages/click/decorators.py", line 270, in callback
    raise RuntimeError('Could not determine version')
RuntimeError: Could not determine version
```

I also tried `pip install mlflow` instead of `conda install mlflow` in a clone env and it worked all right. So I thought this might be related to conda-forge instead of mlflow itself...

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
alembic                   1.2.1                      py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                1.2.0                    py37_0    conda-forge
backports                 1.0                        py_2    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.13.0           py37h33e799b_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
configparser              3.7.3                    py37_1    conda-forge
cryptography              2.7              py37h212c5bf_0    conda-forge
databricks-cli            0.9.0                      py_0    conda-forge
docker-py                 4.1.0                    py37_0    conda-forge
docker-pycreds            0.4.0                      py_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
flask                     1.1.1                      py_1    conda-forge
gitdb2                    2.0.6                      py_0    conda-forge
gitpython                 3.0.3                      py_0    conda-forge
gorilla                   0.3.0                      py_0    conda-forge
gunicorn                  19.9.0                py37_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcxx                    9.0.0                         0    conda-forge
libcxxabi                 9.0.0                         0    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h4bb4525_2    conda-forge
libprotobuf               3.10.0               hd174df1_0    conda-forge
llvm-openmp               9.0.0                h40edb58_0    conda-forge
mako                      1.1.0                      py_0    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
mlflow                    1.2.0                      py_1    conda-forge
mlflow-ui-dbg             1.2.0                         1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.17.2           py37h6b0580a_0    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.1           py37h86efe34_0    conda-forge
pip                       19.3                     py37_0    conda-forge
protobuf                  3.10.0           py37h4a8c4bd_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h01d97ff_0    conda-forge
querystring_parser        1.2.4                      py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
setuptools                41.4.0                   py37_0    conda-forge
simplejson                3.16.0          py37h1de35cc_1002    conda-forge
six                       1.12.0                py37_1000    conda-forge
smmap2                    2.0.5                      py_0    conda-forge
sqlalchemy                1.3.10           py37h0b31af3_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
sqlparse                  0.3.0                      py_0    conda-forge
tabulate                  0.8.5                      py_0    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
urllib3                   1.25.6                   py37_0    conda-forge
websocket-client          0.56.0                   py37_0    conda-forge
werkzeug                  0.16.0                     py_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : mlflowtest
    active env location : /Users/user/miniconda/envs/mlflowtest
            shell level : 1
       user config file : /Users/user/.condarc
 populated config files : /Users/user/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /Users/user/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/user/miniconda/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /Users/user/miniconda/envs
                          /Users/user/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : /Users/user/.netrc
           offline mode : False
```
</details>

To reproduce the error message:
 - the way I installed miniconda:
```
$ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
$ bash ~/miniconda.sh -b -p $HOME/miniconda
$ export PATH="$HOME/miniconda/bin:$PATH"
```
 - the way I add `conda-forge`:
```
$ conda config --add channels conda-forge
$ conda config --set channel_priority strict
```
 - the way I created virtual env:
```
$ conda create -n mlflowtest python mlflow
```
<details>

```
Collecting package metadata (current_repodata.json): done
Solving environment: done
## Package Plan ##

  environment location: /Users/user/miniconda/envs/mlflowtest

  added / updated specs:
    - mlflow
    - python


The following NEW packages will be INSTALLED:

  alembic            conda-forge/noarch::alembic-1.2.1-py_0
  appdirs            conda-forge/noarch::appdirs-1.4.3-py_1
  asn1crypto         conda-forge/osx-64::asn1crypto-1.2.0-py37_0
  backports          conda-forge/noarch::backports-1.0-py_2
  bzip2              conda-forge/osx-64::bzip2-1.0.8-h01d97ff_1
  ca-certificates    conda-forge/osx-64::ca-certificates-2019.9.11-hecc5488_0
  certifi            conda-forge/osx-64::certifi-2019.9.11-py37_0
  cffi               conda-forge/osx-64::cffi-1.13.0-py37h33e799b_0
  chardet            conda-forge/osx-64::chardet-3.0.4-py37_1003
  click              conda-forge/noarch::click-7.0-py_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.2.2-py_0
  configparser       conda-forge/osx-64::configparser-3.7.3-py37_1
  cryptography       conda-forge/osx-64::cryptography-2.7-py37h212c5bf_0
  databricks-cli     conda-forge/noarch::databricks-cli-0.9.0-py_0
  docker-py          conda-forge/osx-64::docker-py-4.1.0-py37_0
  docker-pycreds     conda-forge/noarch::docker-pycreds-0.4.0-py_0
  entrypoints        conda-forge/osx-64::entrypoints-0.3-py37_1000
  flask              conda-forge/noarch::flask-1.1.1-py_1
  gitdb2             conda-forge/noarch::gitdb2-2.0.6-py_0
  gitpython          conda-forge/noarch::gitpython-3.0.3-py_0
  gorilla            conda-forge/noarch::gorilla-0.3.0-py_0
  gunicorn           conda-forge/osx-64::gunicorn-19.9.0-py37_1000
  idna               conda-forge/osx-64::idna-2.8-py37_1000
  itsdangerous       conda-forge/noarch::itsdangerous-1.1.0-py_0
  jinja2             conda-forge/noarch::jinja2-2.10.3-py_0
  libblas            conda-forge/osx-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/osx-64::libcblas-3.8.0-14_openblas
  libcxx             conda-forge/osx-64::libcxx-9.0.0-0
  libcxxabi          conda-forge/osx-64::libcxxabi-9.0.0-0
  libffi             conda-forge/osx-64::libffi-3.2.1-h6de7cb9_1006
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-2
  liblapack          conda-forge/osx-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.7-h4bb4525_2
  libprotobuf        conda-forge/osx-64::libprotobuf-3.10.0-hd174df1_0
  llvm-openmp        conda-forge/osx-64::llvm-openmp-9.0.0-h40edb58_0
  mako               conda-forge/noarch::mako-1.1.0-py_0
  markupsafe         conda-forge/osx-64::markupsafe-1.1.1-py37h1de35cc_0
  mlflow             conda-forge/noarch::mlflow-1.2.0-py_1
  ncurses            conda-forge/osx-64::ncurses-6.1-h0a44026_1002
  numpy              conda-forge/osx-64::numpy-1.17.2-py37h6b0580a_0
  openssl            conda-forge/osx-64::openssl-1.1.1c-h01d97ff_0
  packaging          conda-forge/noarch::packaging-19.2-py_0
  pandas             conda-forge/osx-64::pandas-0.25.1-py37h86efe34_0
  pip                conda-forge/osx-64::pip-19.3-py37_0
  protobuf           conda-forge/osx-64::protobuf-3.10.0-py37h4a8c4bd_0
  pycparser          conda-forge/osx-64::pycparser-2.19-py37_1
  pyopenssl          conda-forge/osx-64::pyopenssl-19.0.0-py37_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.2-py_0
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py37_0
  python             conda-forge/osx-64::python-3.7.3-h93065d6_1
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  python-editor      conda-forge/noarch::python-editor-1.0.4-py_0
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  pyyaml             conda-forge/osx-64::pyyaml-5.1.2-py37h01d97ff_0
  querystring_parser conda-forge/noarch::querystring_parser-1.2.4-py_0
  readline           conda-forge/osx-64::readline-8.0-hcfe32e1_0
  requests           conda-forge/osx-64::requests-2.22.0-py37_1
  setuptools         conda-forge/osx-64::setuptools-41.4.0-py37_0
  simplejson         conda-forge/osx-64::simplejson-3.16.0-py37h1de35cc_1002
  six                conda-forge/osx-64::six-1.12.0-py37_1000
  smmap2             conda-forge/noarch::smmap2-2.0.5-py_0
  sqlalchemy         conda-forge/osx-64::sqlalchemy-1.3.10-py37h0b31af3_0
  sqlite             conda-forge/osx-64::sqlite-3.30.1-h93121df_0
  sqlparse           conda-forge/noarch::sqlparse-0.3.0-py_0
  tabulate           conda-forge/noarch::tabulate-0.8.5-py_0
  tk                 conda-forge/osx-64::tk-8.6.9-h2573ce8_1003
  urllib3            conda-forge/osx-64::urllib3-1.25.6-py37_0
  websocket-client   conda-forge/osx-64::websocket-client-0.56.0-py37_0
  werkzeug           conda-forge/noarch::werkzeug-0.16.0-py_0
  wheel              conda-forge/osx-64::wheel-0.33.6-py37_0
  xz                 conda-forge/osx-64::xz-5.2.4-h1de35cc_1001
  yaml               conda-forge/osx-64::yaml-0.1.7-h1de35cc_1001
  zlib               conda-forge/osx-64::zlib-1.2.11-h0b31af3_1006


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate mlflowtest
#
# To deactivate an active environment, use
#
#     $ conda deactivate

```
</details>

**Comment by felipemmelo** [comment]
Had the very same issue.

**Comment by arthurp** [comment]
It appears this issue still occasionally happens because conda will, at least sometimes, choose to install mlflow 1.2.0 instead of the latest. I'm not sure why. It does report there are multiple solves. I don't see why it wouldn't choose the newest versions. mamba does not have this interest.

The workaround is to specify `mlflow>=1.20` or similar.

**Comment by xhochy** [comment]
@arthurp Do you think there is anything we could do here? I will close the issue for now as recent versions working means we resolved this.
